<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>ShowBPM</AssemblyName>
    <RootNamespace>ShowBPM.Mobile</RootNamespace>
    <Version>1.2.1</Version>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Optimize>true</Optimize>
    <DebugType>embedded</DebugType>
    <Deterministic>true</Deterministic>
  </PropertyGroup>

  <ItemGroup>
    <Analyzer Include="..\References\StArray.ModManager.Analyzer.dll" />
    <Reference Include="StArray.ModManager">
      <HintPath>..\References\StArray.ModManager.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="ImGui.NET">
      <HintPath>..\References\ImGui.NET.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

</Project>
